CREATE TABLE IF NOT EXISTS professor (
	id SERIAL PRIMARY KEY,
	nome VARCHAR(50) NOT NULL,
	idade INTEGER 
);

CREATE TABLE ALUNO(
	ID SERIAL PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	ANO_ESCOLAR INTEGER
);

CREATE TABLE DIRETOR(
	BONUS DECIMAL(5,2)
) INHERITS (PROFESSOR);
